ui: mocha-bdd
browsers:
    - name: chrome
      version: 30..latest
    - name: firefox
      version: 27..latest
    - name: opera
      version: 12..latest
    - name: ie
      version: 10..latest
    - name: safari
      version: 6..latest
